export const mutations = {
  SET_CITY_NAME: 'SET_CITY_NAME',
  SET_DAYS: 'SET_DAYS',
  SET_HINT_DISPLAYING: 'SET_HINT_DISPLAYING',
  SET_LOADING: 'SET_LOADING'
};

export const actions = {
  SET_UNIQUE_DAYS: 'SET_UNIQUE_DAYS'
};
